# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 7051909502d5cfcfdb37fdacd56d77559a60ac363799656ab8bda14154f195f6989201cae919dc95d913cec224fc4cebdde2cbff95de95d8f7171a795436d612

test:
  secret_key_base: dc1124ea0e9dd555c4c315cdc822740fa894151821da26de25f0948f6fa16773cc8027d6fe097b8d2ca47539e7e4f0daaa872be55867fb319c0c8799cde868fe

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
